[package]
name = "sibyl"
version = "0.6.1"
edition = "2018"
description = "An OCI-based (synchronous or asynchronous) interface between Rust applications and Oracle databases"
authors = ["Alex Demenchuk <alexander.demenchuk@gmail.com>"]
license = "MIT"
keywords = ["database","sql","oracle","ffi","async"]
categories = ["database"]
repository = "https://github.com/quietboil/sibyl"
homepage = "https://quietboil.github.io/sibyl"
documentation = "https://docs.rs/sibyl"

[dependencies]
libc = "0.2"
once_cell = "1.9"
parking_lot = "0.11"
tokio-rt = { version = "1", features = ["rt"], optional = true, package = "tokio" }

[dev-dependencies]
tokio-rt = { version = "1", features = ["rt", "rt-multi-thread"], package = "tokio" }

[features]
blocking = []
nonblocking = ["tokio-rt"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]