[package]
name = "sibyl"
version = "0.4.1"
edition = "2018"
description = "An OCI-based interface between Rust applications and Oracle databases"
authors = ["Alex Demenchuk <alexander.demenchuk@gmail.com>"]
license = "MIT"
keywords = ["database","sql","oracle","oci","ffi"]
categories = ["database"]
repository = "https://github.com/quietboil/sibyl"
homepage = "https://github.com/quietboil/sibyl"
documentation = "https://docs.rs/sibyl"

[dependencies]
libc = "0.2"
once_cell = "1.8"

[features]
default = []
nonblocking = []
